spring.application.name=SWP

# MS SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=HackathonDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect

# =====================
# JWT CONFIG (FIX ERROR)
# =====================
app.jwt-secret=swp391_super_secret_key_2026_change_me
# 1 day
app.jwt-access-token-expiration-ms=86400000
# 7 days
app.jwt-refresh-token-expiration-ms=604800000

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=TRACE
